language: bash
install:
  - wget http://ftp.debian.org/debian/pool/main/s/shellcheck/shellcheck_0.3.7-5_amd64.deb
  - dpkg -x shellcheck_0.3.7-5_amd64.deb shellcheck/
script:
  - shellcheck/usr/bin/shellcheck script/*
sudo: false
